version: "3.3"

services:
  app:
    container_name: express-app
    build: .
    ports:
      - "3001:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    restart: unless-stopped
